apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark  
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.2.2
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark
  source:
    path: argo-cd/overlays/minikube
    repoURL: https://github.com/flavioaiello/gitops
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argo-events
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark
  source:
    path: argo-events
    repoURL: https://github.com/flavioaiello/gitops
    targetRevision: HEAD
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark
  source:
    path: argo-rollouts
    repoURL: https://github.com/flavioaiello/gitops
    targetRevision: HEAD
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo-workflows
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark
  source:
    path: argo-workflows
    repoURL: https://github.com/flavioaiello/gitops
    targetRevision: HEAD
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true