apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: eac
spec:
  forProvider:
    locations:
    - us-east1-b
    - us-east1-c
    - us-east1-d
    clusterRef:
      name: jira
    initialNodeCount: 1
    config:
      preemptible: true
      machineType: e2-standard-2
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false
