apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allspark
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allspark
  source:
    path: allspark/overlays/eks
    repoURL: https://github.com/flavioaiello/gitops
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true