apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  labels:
    app: jira
spec:
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: jira-series
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
